language: php

php:
    - 5.5

before_install:
    - sudo chmod 0777 -R app/logs/ app/cache/

install:
    - composer install -n --prefer-source

before_script:
    - php app/console doctrine:database:create
    - php app/console doctrine:schema:create
    - php app/console doctrine:fixtures:load --no-interaction

script:
    - bin/phpunit -c app --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
