woe_notification:
    resource: "@WoeNotificationBundle/Resources/config/routing.yml"
    prefix:   /

woe_event:
    resource: "@WoeEventBundle/Resources/config/routing.yml"
    prefix:   /

woe_web:
    resource: "@WoeWebBundle/Resources/config/routing.yml"
    prefix:   /
