woe_event:
    resource: "@WoeEventBundle/Resources/config/routing.yml"
    prefix:   /

woe_web:
    resource: "@WoeWebBundle/Resources/config/routing.yml"
    prefix:   /

woe_filter:
    resource: "@WoeFilterBundle/Resources/config/routing.yml"
    prefix:   /

