services:
#    woe_crawler.example:
#        class: Woe\CrawlerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    woe_crawler.bilietai_crawler:
        class: Woe\CrawlerBundle\Services\Crawler\BilietaiCrawler
        arguments:
            - "@woe_crawler.bilietai_parser"

    woe_crawler.bilietai_parser:
        class: Woe\CrawlerBundle\Services\Parser\BilietaiEventParser
