woe_web_homepage:
    path: /
    defaults: { _controller: WoeEventBundle:Default:index }

woe_web_event:
    path: /event/{id}
    defaults: { _controller: WoeEventBundle:Default:event }

woe_event_search:
    path:     /search
    defaults: { _controller: WoeEventBundle:Default:search }

woe_web_tag:
    path: /tag/{id}
    defaults: { _controller: WoeEventBundle:Default:tag }
