woe_event_homepage:
    path:     /hello/{name}
    defaults: { _controller: WoeEventBundle:Default:index }

woe_event_search:
    path:     /search
    defaults: { _controller: WoeEventBundle:Default:search }
